version: '3.9'

name: rails6dummy

services:
  psql:
    image: postgres:15.1-bullseye
    user: root
    environment:
      POSTGRES_PASSWORD: qwerty
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./db/PGSQL:/var/lib/postgresql/data/pgdata

  rails:
    tty: true
    stdin_open: true
    image: iamteacher/rails7:latest
    working_dir: /home/lucky/rails6dummy
    volumes:
      - .:/home/lucky/rails6dummy
    ports:
      - 3000:3000
    depends_on:
      - psql
